volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: dyachenkomark/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media/

  frontend:
    image: dyachenkomark/kittygram_frontend
    env_file: .env
    command: sh -c "cp -r /app/build/. /frontend_static/"
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: dyachenkomark/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media/
    ports:
      - 9000:80

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Деплой успешно выполнен!
